import Head from "next/head";
import React, { useState, useEffect } from "react";
import Anniversary from "../components/anniversary";
import Countdowns from "../components/countdowns";
import Background from "../components/background";
import Footer from "../components/footer";

import dayjs from "dayjs";
import duration from "dayjs/plugin/duration";

export default function Home() {
  dayjs.locale("pl");
  dayjs.extend(duration);
  const [timerLastStreamYears, setLastStreamYears] = useState("0");
  const [timerLastStreamMonths, setLastStreamMonths] = useState("0");
  const [timerLastStreamDays, setLastStreamDays] = useState("0");
  const [timerLastStreamHours, setLastStreamHours] = useState("0");
  const [timerLastStreamMinutes, setLastStreamMinutes] = useState("0");
  const [timerLastStreamSeconds, setLastStreamSeconds] = useState("0");

  const [timerAnniversaryYears, setAnniversaryYears] = useState("00");
  const [timerAnniversaryMonths, setAnniversaryMonths] = useState("00");
  const [timerAnniversaryDays, setAnniversaryDays] = useState("00");
  const [timerAnniversaryHours, setAnniversaryHours] = useState("00");
  const [timerAnniversaryMinutes, setAnniversaryMinutes] = useState("00");
  const [timerAnniversarySeconds, setAnniversarySeconds] = useState("00");

  const AnniversaryCountdown = () => {
    const lastStream = dayjs("2021-09-09T22:35:00.000Z");

    setInterval(() => {
      const now = dayjs();
      const anniversaryTitle = dayjs.duration(now.diff(lastStream));
      const anniversaryDate = lastStream.add(
        anniversaryTitle.add(1, "year").years(),
        "year"
      );
      const duration = dayjs.duration(anniversaryDate.diff(now));

      const seconds = duration.seconds().toString().padStart(2, "0");
      const minutes = duration.minutes().toString().padStart(2, "0");
      const hours = duration.hours().toString().padStart(2, "0");
      const days = duration.days().toString().padStart(2, "0");
      const months = duration.months().toString().padStart(2, "0");
      const years = `${
        anniversaryTitle.years() >= 1
          ? anniversaryTitle.add(1, "year").years().toString()
          : ""
      } Rocznica bez Streama`;

      setAnniversaryYears(years);
      setAnniversaryMonths(months);
      setAnniversaryDays(days);
      setAnniversaryHours(hours);
      setAnniversaryMinutes(minutes);
      setAnniversarySeconds(seconds);
    });
  };

  const LastStream = () => {
    const lastStream = dayjs("2021-09-09T22:35:00.000Z");

    setInterval(() => {
      const now = dayjs();
      const duration = dayjs.duration(now.diff(lastStream));

      console.log(duration);

      const seconds = duration.seconds().toString();
      const minutes = duration.minutes().toString();
      const hours = duration.hours().toString();
      const days = duration.days().toString();
      const months = duration.months().toString();
      const years = duration.years().toString();

      setLastStreamYears(years);
      setLastStreamMonths(months);
      setLastStreamDays(days);
      setLastStreamHours(hours);
      setLastStreamMinutes(minutes);
      setLastStreamSeconds(seconds);
    });
  };

  useEffect(() => {
    AnniversaryCountdown();
    LastStream();
  });

  return (
    <>
      <Head>
        <title>vanRooD Date</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          href="https://static-cdn.jtvnw.net/jtv_user_pictures/351d2d6e-6b82-43aa-a5db-67971e726815-profile_image-600x600.png"
        />
      </Head>

      <div className="z-[1] w-[600px] min-h-screen flex flex-col items-center justify-center">
        <Anniversary
          timerYears={timerAnniversaryYears}
          timerMonths={timerAnniversaryMonths}
          timerDays={timerAnniversaryDays}
          timerHours={timerAnniversaryHours}
          timerMinutes={timerAnniversaryMinutes}
          timerSeconds={timerAnniversarySeconds}
        />
        <Countdowns
          timerYears={timerLastStreamYears}
          timerMonths={timerLastStreamMonths}
          timerDays={timerLastStreamDays}
          timerHours={timerLastStreamHours}
          timerMinutes={timerLastStreamMinutes}
          timerSeconds={timerLastStreamSeconds}
        />
        <Footer />
      </div>
      <Background />
    </>
  );
}
